name: stonekaiju
favicon: null
layout_spectrum: 0.51504
typography_spectrum: 0.23963
title: Stone Kaiju
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d4d5da'
    - '#737478'
    - '#fc520b'
    - '#80180f'
  brandStrength: 0.6783858130220324
  lightness: 0.18235241435468197
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
