name: stonekaiju
favicon: null
layout_spectrum: 0.28168
typography_spectrum: 0.23963
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d081c'
    - '#ffffff'
    - '#1e3cf2'
    - '#b02393'
    - '#85d1f5'
  brandStrength: 0.6783858130220324
  lightness: 0.18235241435468197
  saturation: 0.1875
  rhythmicContrast: 0.027802428929135203
purpose: []
