name: stonekaiju
favicon: null
layout_spectrum: 0.7159664137288928
typography_spectrum: 0.8303319467231631
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.6783858130220324
  lightness: 0.18235241435468197
  saturation: 0.13419971568509936
  rhythmicContrast: 0.027802428929135203
purpose: []
